### ISSUE TITLE
Dont compare python and C++

### ISSUE THREAD

**Issue by sushil-bharati** [arrufat/dlib-pytorch-benchmark#3]
!!!

**Comment by arrufat** [comment]
Actually, I'm not: almost no python code is run on these benchmarks. Python is just an API language to access all the Pytorch core functionality (written in C++ and CUDA). I like to think of it as the UNIX shell when you pipe several C programs like cat, awk, sort, uniq...

If I was doing some post processing (like NMS, etc) then the comparison wouldn't be fair, but it's not the case, I'm just measuring the time it takes to process an image for each toolkit.

I was going to put the Pytorch C++ frontend code, but there was no difference in inference time or memory usage. You can try it for yourself.


However, I need to update the backprop code, there are some mistakes in the Pytorch version (which I already mention in the README).
